### ISSUE TITLE
Composer-Fehler

### ISSUE THREAD

**Issue by srhinow** [ErdmannFreunde/euf_nutshell_kit#1]
Ich wollte eben euer framework mal in ner Contao 3.5.26 Installation ausprobieren. Dazu habe ich:
`php composer.phar require erdmannfreunde/euf_nutshell_kit` eingegeben.

Dann gab er mir folgendes als Fehler zurück:
***
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for erdmannfreunde/euf_nutshell_kit ^0.2.0 -> satisfiable by erdmannfreunde/euf_nutshell_kit[0.2.0].
    - erdmannfreunde/euf_nutshell_kit 0.2.0 requires contao/core-bundle >=3.5,<=3.5.9999 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.`
***
So wie ich das verstehe, referenziert das Modul auf contao/core-bundle. Das aber evtl. für die alte 3.5.x Version so nicht heißt. Denn wenn ich mir die Contao- composer.json anschaue, dann heißt diese contao/core und nicht contao/core-bundle

**Comment by denniserdmann** [comment]
Hmm, eigentlich sollte das so funktionieren. Hast du die Paketverwaltung für Contao installiert? 
Habe es gerade nochmal mal getestet, auch in einer Contao 3.5 gibt es ein `contao/core-bundle`. Versuch mal im ersten Schritt `php composer.phar install` auszuführen. Ich vermute, dass die Abhängigkeiten wie `core-bundle` bei dir noch nicht installiert sind. Danach sollte auch die Installation des *Nutshell Starterkits* funktionieren

**Comment by srhinow** [comment]
muss ich unbedingt in Contao die composer-Paketverwaltung installieren? Ich habe gehofft, das ich neben dem alten ER per Comandline Pakete via composer installieren kann. Da ja eine composer.json im Contao-ROOT exisitert, dachte ich das ich normal per composer require [PAKETNAME] (Linux-zsh) weitere Pakete installieren kann.

**Comment by denniserdmann** [comment]
Ja, unter Contao 3.5 musst du dich aktiv für die Paketverwaltung entscheiden, da sonst der alte Erweiterungskatalog von Contao noch aktiv ist. Nach der Installation der Paketverwaltung git es im Contao-Root auch einen neuen Ordner `composer` indem du weitere Pakete installieren kannst.

**Comment by srhinow** [comment]
ja mit dem installierten composer-client geht es.
