### ISSUE TITLE
Hard dependency of Conato core 4.4.* prevents composer update to Contao 4.9.*

### ISSUE THREAD

**Issue by Sigma-90** [ErdmannFreunde/euf_nutshell_kit#16]
Line 14 of composer.json lists:
`"contao/manager-bundle": "4.4.*",`

This causes update installations from Contato 4.4.x to the current LTS version 4.9 to fail. There should not be significant compatibility issues between 4.4 and 4.9, so I would therefore suggest to simply change that single line to
`"contao/manager-bundle": "^4.4",`
and check if that works.

**Comment by denniserdmann** [comment]
Do you use the nutshell starterkit with `composer create-project` as suggested here: https://github.com/erdmannfreunde/euf_nutshell_kit#create-composer-project  ?

In this case, it's up to you to change the version inside your project `composer.json`. The starterkit is not supposed to work as bundle, but as starting point for your project.

**Comment by Sigma-90** [comment]
Apparently it was installed as a prerequisite for euf_grid and euf_hero, so in order to keep those working I figured that I had to keep it around. I finally got around composer denying the update to Contao 4.9 by manually changing both the composer.json in vendors/erdmannfreunde/euf_nutshell_kit as well as its related entry in the main composer lockfile in the way I described above, but as soon as anyone tries a reinstallation of the kit, it will likely break again. So an update that simply addresses the compatibility issue would still go a long way of saving a lot of people from experiencing those problems I had.

**Comment by denniserdmann** [comment]
We will not change the composer.json as your usage differ from our proposed usage. But you have two options: 

1. check if you really need the starterkit. If you just need the nutshell framework, simply install [euf_nutshell](https://github.com/erdmannfreunde/euf_nutshell). You can even import a [nutshell.scss](https://github.com/erdmannfreunde/euf_nutshell/blob/master/files/nutshell/scss/nutshell.scss)
2. if you already used the files inside the starterkit, copy them, install `euf_nutshell` and remove the starterkit from your composer.json.

We will not change the composer.json inside starterkit as we have several branches which install different contao versions, for example: https://github.com/erdmannfreunde/euf_nutshell_kit/tree/4.9

**FYI:** There's also an even newer version of the [nutshell framework + starterkit](https://github.com/nutshell-framework/starterkit) that you might want to test.
