### ISSUE TITLE
Setup an individual folder name needs to rebuild symlinks

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/euf_nutshell_kit#5]
When using the installer, i choose a the folder name `theme` . After installation finished i was wondering why i can choose a css file in the backend but get an error when trying to load the css in the frontend. 

Turns out there was a symlink to the default folder name `starterkit`
- Before symlinking: `web/files/starterkit`
- After symlinking: `web/files/theme`

Maybe we should add this to the readme file or put it into the nutshell installer.

**Comment by richardhj** [comment]
I guess it is because I added the `.public` in 175d44583be4b9b05dd89db8ff46d77b6014014c.
